# Disable some of these excessive warnings
# Some of these are internal to goreleaser and cannot be fixed.

FormulaAudit/Version:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

FormulaAudit/ComponentsOrder:
  Enabled: false

FormulaAudit/DependencyOrder:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/TrailingBodyOnMethodDefinition:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
